name: mirror
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Install Mercurial and hg-git
        shell: bash
        run: sudo apt-get install mercurial mercurial-git --no-install-recommends -y
      - name: Push
        shell: bash
        run: |
          hg clone http://hg.code.sf.net/p/scintilla/code
          pushd code
          hg push https://orbitalquark:${{ secrets.PAT }}@github.com/orbitalquark/scintilla-mirror2.git
          popd
