name: mirror
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Install Mercurial and hg-git
        shell: bash
        run: sudo apt-get install mercurial mercurial-git --no-install-recommends -y
      - name: Create hgrc
        shell: bash
        run: |
          echo '[extensions]' > ~/.hgrc
          echo 'hggit =' >> ~/.hgrc
          echo '[auth]' >> ~/.hgrc
          echo 'github.prefix = github.com' >> ~/.hgrc
          echo 'github.username = orbitalquark' >> ~/.hgrc
          echo 'github.password = ${{ secrets.PAT }}' >> ~/.hgrc
      - name: Pull and push
        shell: bash
        run: |
          hg clone https://github.com/orbitalquark/scintilla-mirror2.git
          hg clone http://hg.code.sf.net/p/scintilla/code
          pushd code
          hg push ../scintilla-mirror2
          popd
          hg push
