name: mirror
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Mercurial and hg-git
        shell: bash
        run: sudo apt-get install mercurial mercurial-git --no-install-recommends -y
      - name: Create hgrc
        shell: bash
        run: |
          echo '[extensions]' > ~/.hgrc
          echo 'hggit =' >> ~/.hgrc
          echo '[git]' >> ~/.hgrc
          echo 'branch_bookmark_suffix = _git' >> ~/.hgrc
          echo '[auth]' >> ~/.hgrc
          echo 'github.prefix = github.com' >> ~/.hgrc
          echo 'github.username = orbitalquark' >> ~/.hgrc
          echo 'github.password = ${{ secrets.PAT }}' >> ~/.hgrc
      - name: Push
        shell: bash
        run: |
          hg clone http://hg.code.sf.net/p/scintilla/code
          pushd code
          hg bookmark default_git
          url="https://github.com/orbitalquark/scintilla-mirror.git"
          if [ -z "`hg out -b default $url | grep -o 'no changes found'`" ]; then hg push $url; fi
          popd
