name: mirror
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Install Mercurial and hg-git
        shell: bash
        run: sudo apt-get install mercurial mercurial-git --no-install-recommends -y
      - name: Create hgrc
        shell: bash
        run: |
          echo > ~/.hgrc << EOF
          [auth]
          github.prefix = https://github.com
          github.username = orbitalquark
          github.password = ${{ secrets.PAT }}
          EOF
      - name: Pull and push
        shell: bash
        run: |
          hg clone https://orbitalquark:${{ secrets.PAT }}@github.com/orbitalquark/scintilla-mirror2.git
          pushd scintilla-mirror2
          hg pull http://hg.code.sf.net/p/scintilla/code
          hg push
